### ISSUE TITLE
TPS loss issue

### ISSUE THREAD

**Issue by AngellitoX** [pop4959/LWCX#114]
**LWC Version (/lwc admin version):** 2.2.5
**Server version (/version):** 
1.15.2 Paper 372
**Short five word summary of issue:** 
Extremely bad performance causing TPS Loss
**Detailed description of problem:**

https://timings.aikar.co/?id=d60b4d2be52240c8b8c0b6238bccf0bf

**If there was an error in console, put it here:**
```
com.griefcraft.scripting.ModuleException: java.sql.SQLException: Parameter index out of range (2 > number of parameters, which is 1).
	at com.griefcraft.sql.Database.printException(Database.java:196) ~[?:?]
	at com.griefcraft.sql.PhysDB.loadProtections(PhysDB.java:1061) ~[?:?]
	at com.griefcraft.modules.flag.MagnetModule$MagnetTask.run(MagnetModule.java:149) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-372]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.sql.SQLException: Parameter index out of range (2 > number of parameters, which is 1).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[patched_1.15.2.jar:git-Paper-372]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[patched_1.15.2.jar:git-Paper-372]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[patched_1.15.2.jar:git-Paper-372]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[patched_1.15.2.jar:git-Paper-372]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3382) ~[patched_1.15.2.jar:git-Paper-372]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3367) ~[patched_1.15.2.jar:git-Paper-372]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3406) ~[patched_1.15.2.jar:git-Paper-372]
	at com.mysql.jdbc.PreparedStatement.setInt(PreparedStatement.java:3357) ~[patched_1.15.2.jar:git-Paper-372]
	at com.griefcraft.sql.PhysDB.loadProtections(PhysDB.java:1052) ~[?:?]
	... 8 more
```

**Comment by pop4959** [comment]
TPS loss appears to be due to excessive use of the magnet module. If this is an unintended feature on your server, feel free to disable magnet in `magnet.yml`. Otherwise you will need to limit its use. Overuse of magnet is similar in performance to overusing hoppers.

The errors may be caused by history being enabled. This is already a known issue when using MySQL. If you are not using history (mostly used for using economy with LWC protections) you may disable that in `core.yml`. Otherwise, they are not all too harmful and you should be able to ignore them generally.
