### ISSUE TITLE
MySQL database doesn't reconnect after connection failure

### ISSUE THREAD

**Issue by Phoenix616** [pop4959/LWCX#115]
**LWC Version (/lwc admin version):** 2.2.4-a88d70a (I know this isn't latest but I don't see anything related to MySQL connection changes)
**Server version (/version):** git-Origami-"6593510" (basically Paper 1.15.2 b371)

**Short five word summary of issue:** MySQL doesn't reconnect

**Detailed description of problem:**

When the connection to the MySQL fails (e.g. due to a restart or network issues) the plugin does not auto-reconnect and throws errors on any protectioni nteraction.

**If there was an error in console, put it here:**
```
[00:36:28] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to LWC v2.2.4-a88d70a
com.griefcraft.scripting.ModuleException: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 3,735,612 milliseconds ago.  The last packet sent successfully to the server was 3,447,243 milliseconds ago.
        at com.griefcraft.sql.Database.printException(Database.java:198) ~[?:?]
        at com.griefcraft.sql.PhysDB.resolveProtections(PhysDB.java:861) ~[?:?]
        at com.griefcraft.sql.PhysDB.resolveProtection(PhysDB.java:881) ~[?:?]
        at com.griefcraft.sql.PhysDB.loadProtection(PhysDB.java:972) ~[?:?]
        at com.griefcraft.sql.PhysDB.loadProtection(PhysDB.java:934) ~[?:?]
        at com.griefcraft.lwc.LWC.findProtection(LWC.java:1362) ~[?:?]
        at com.griefcraft.lwc.LWC.findProtection(LWC.java:1345) ~[?:?]
        at com.griefcraft.listeners.LWCEntityListener.entityCreatedByPlayer(LWCEntityListener.java:216) ~[?:?]
        at com.griefcraft.listeners.LWCEntityListener.onCreateSpawn(LWCEntityListener.java:199) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor41.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[craftbukkit.jar:git-Origami-"6593510"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[craftbukkit.jar:git-Origami-"6593510"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[craftbukkit.jar:git-Origami-"6593510"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[craftbukkit.jar:git-Origami-"6593510"]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:639) ~[craftbukkit.jar:git-Origami-"6593510"]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:560) ~[craftbukkit.jar:git-Origami-"6593510"]
        at net.minecraft.server.v1_15_R1.WorldServer.addEntity0(WorldServer.java:1267) ~[craftbukkit.jar:git-Origami-"6593510"]
        at net.minecraft.server.v1_15_R1.WorldServer.addEntity(WorldServer.java:1175) ~[craftbukkit.jar:git-Origami-"6593510"]
        at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.addEntity(CraftWorld.java:1965) ~[craftbukkit.jar:git-Origami-"6593510"]
        at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawn(CraftWorld.java:1972) ~[craftbukkit.jar:git-Origami-"6593510"]
        at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawn(CraftWorld.java:1556) ~[craftbukkit.jar:git-Origami-"6593510"]
        at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawnEntity(CraftWorld.java:782) ~[craftbukkit.jar:git-Origami-"6593510"]
        at io.github.apfelcreme.MbPetsNoLD.Pet.Pet.lambda$spawn$0(Pet.java:361) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[craftbukkit.jar:git-Origami-"6593510"]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[craftbukkit.jar:git-Origami-"6593510"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1286) ~[craftbukkit.jar:git-Origami-"6593510"]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:432) ~[craftbukkit.jar:git-Origami-"6593510"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1203) ~[craftbukkit.jar:git-Origami-"6593510"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:992) ~[craftbukkit.jar:git-Origami-"6593510"]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 3,735,612 milliseconds ago.  The last packet sent successfully to the server was 3,447,243 milliseconds ago.
        at jdk.internal.reflect.GeneratedConstructorAccessor227.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[craftbukkit.jar:git-Origami-"6593510"]
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990) ~[craftbukkit.jar:git-Origami-"6593510"]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2512) ~[craftbukkit.jar:git-Origami-"6593510"]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675) ~[craftbukkit.jar:git-Origami-"6593510"]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465) ~[craftbukkit.jar:git-Origami-"6593510"]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912) ~[craftbukkit.jar:git-Origami-"6593510"]
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2020) ~[craftbukkit.jar:git-Origami-"6593510"]
        at com.griefcraft.sql.PhysDB.resolveProtections(PhysDB.java:858) ~[?:?]
        ... 28 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.InputStream.available()" because "this.mysqlInput" is null
        at com.mysql.jdbc.MysqlIO.clearInputStream(MysqlIO.java:892) ~[craftbukkit.jar:git-Origami-"6593510"]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2471) ~[craftbukkit.jar:git-Origami-"6593510"]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675) ~[craftbukkit.jar:git-Origami-"6593510"]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465) ~[craftbukkit.jar:git-Origami-"6593510"]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912) ~[craftbukkit.jar:git-Origami-"6593510"]
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2020) ~[craftbukkit.jar:git-Origami-"6593510"]
        at com.griefcraft.sql.PhysDB.resolveProtections(PhysDB.java:858) ~[?:?]
        ... 28 more

```

**Comment by pop4959** [comment]
This is a known issue, although it doesn't seem to happen frequently, and it's not clear to me what the issue could be. In LWC's code, the `autoReconnect` property is set to true already for MySQL databases:

https://github.com/pop4959/LWCX/blob/e0ff3ddd19e32f913f149e48803e37db4762665d/src/main/java/com/griefcraft/sql/Database.java#L234

Increasing the value of the `wait_timeout` server system variable has been known to help, but is a workaround. This needs further investigation.

**Comment by Haarolean** [comment]
Huh, I know exactly how to fix this and probably why `autoReconnect` does no good at all. I was experiencing such problems with many different plugins back in time when LWCX had no 'X' in name.
I'll propose a change to fix this soon.

**Comment by pop4959** [comment]
Has hopefully been fixed by #126 (thanks @Haarolean). If anyone is still experiencing issues please make a new issue.

**Comment by seema84** [comment]
lwcx Version: v2.4.0
Paper 1.21.1

So, I'm still having the same problem.
A MySQL reconnect does not work for me.

> [Server thread/WARN]: [LWC] Task #9 for LWC v2.4.0 generated an exception
com.griefcraft.scripting.ModuleException: com.griefcraft.scripting.ModuleException: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
	at LWC-2.4.0.jar/com.griefcraft.sql.Database.printException(Database.java:185) ~[LWC-2.4.0.jar:?]
	at LWC-2.4.0.jar/com.griefcraft.sql.PhysDB.loadProtections(PhysDB.java:1064) ~[LWC-2.4.0.jar:?]
	at LWC-2.4.0.jar/com.griefcraft.modules.flag.MagnetModule$MagnetTask.run(MagnetModule.java:154) ~[LWC-2.4.0.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: com.griefcraft.scripting.ModuleException: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
	at LWC-2.4.0.jar/com.griefcraft.sql.Database.printException(Database.java:185) ~[LWC-2.4.0.jar:?]
	at LWC-2.4.0.jar/com.griefcraft.sql.PhysDB.resolveProtections(PhysDB.java:864) ~[LWC-2.4.0.jar:?]
	at LWC-2.4.0.jar/com.griefcraft.sql.PhysDB.loadProtections(PhysDB.java:1062) ~[LWC-2.4.0.jar:?]
	... 9 more
Caused by: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:102) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:81) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:55) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:65) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.jdbc.ConnectionImpl.setSessionMaxRows(ConnectionImpl.java:2594) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1002) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at LWC-2.4.0.jar/com.griefcraft.sql.PhysDB.resolveProtections(PhysDB.java:861) ~[LWC-2.4.0.jar:?]
	at LWC-2.4.0.jar/com.griefcraft.sql.PhysDB.loadProtections(PhysDB.java:1062) ~[LWC-2.4.0.jar:?]
	... 9 more
Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:52) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:95) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:140) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:915) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:586) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.jdbc.ConnectionImpl.setSessionMaxRows(ConnectionImpl.java:2570) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1002) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at LWC-2.4.0.jar/com.griefcraft.sql.PhysDB.resolveProtections(PhysDB.java:861) ~[LWC-2.4.0.jar:?]
	at LWC-2.4.0.jar/com.griefcraft.sql.PhysDB.loadProtections(PhysDB.java:1062) ~[LWC-2.4.0.jar:?]
	... 9 more

**Comment by Haarolean** [comment]
@seema84 could you please raise a new issue? So we don't touch this 6yo artifact
