### ISSUE TITLE
Error on every startup after converting from sqlite to mysql

### ISSUE THREAD

**Issue by brwnie** [pop4959/LWCX#129]
**LWC Version (/lwc admin version):**  2.2.7-dev-a2c6dd9
**Server version (/version):**  git-paper-229

**Short five word summary of issue:**  Startup error post database conversion

**Detailed description of problem:**

On every start up the plugin disables itself due to an error, leaving all chests unprotected.

This occurs on every start up after a transisiton from a local sqlite file to a local mysql database 

**If there was an error in console, put it here:**
```
[23:12:34] [Server thread/ERROR]: Error occurred while enabling LWC v2.2.7-dev-48106d6 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register com.griefcraft.listeners.LWCPlayerListener@5edea2c2 while not enabled
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:636) ~[patched_1.16.3.jar:git-Paper-246]
        at com.griefcraft.lwc.LWCPlugin.registerEvents(LWCPlugin.java:506) ~[?:?]
        at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:402) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-246]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-246]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-246]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-246]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:205) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-246]
        at java.lang.Thread.run(Thread.java:832) [?:?]
[23:12:34] [Server thread/INFO]: Preparing level "world"

```

**Comment by pop4959** [comment]
Can you give the full log, instead of just that error? The one you've shown here doesn't indicate anything except that the plugin was disabled, and that reason is important.

Make sure that you have configured your MySQL connection correctly. This is usually a big stumbling block for a lot of people.

**Comment by brwnie** [comment]
@pop4959 

Full log below, it only started after following startup after  the conversion completed. 

[23:51:14] [Server thread/INFO]: [LWC] Loading LWC v2.2.7-dev-48106d6
[23:51:18] [Server thread/INFO]: [LWC] Enabling LWC v2.2.7-dev-48106d6
[23:51:18] [Server thread/INFO]: [LWC] Connecting to MySQL
[23:51:22] [Server thread/INFO]: [LWC] Failed to connect to MySQL: 0 - Could not create connection to database server. Attempted reconnect 3 times. Giving up.
[23:51:22] [Server thread/INFO]: [LWC] Connection failure cause: Public Key Retrieval is not allowed
[23:51:22] [Server thread/INFO]: [LWC] Disabling LWC v2.2.7-dev-48106d6
[23:51:22] [Server thread/INFO]: [LWC] Flushing protection updates (0)
[23:51:22] [Server thread/ERROR]: Error occurred while enabling LWC v2.2.7-dev-48106d6 (Is it up to date?)

**Comment by pop4959** [comment]
Looks like the issue is printed right there in plain sight. You'll need to fix your MySQL configuration and/or server so that it's able to connect properly. I can't help you much there, since it varies from person to person.

If you're not able to figure it out, SQLite is probably still a good option, especially if you aren't trying to synchronize data for a world across several servers.
