### ISSUE TITLE
"Unable to add new block to lwc_blocks!"

### ISSUE THREAD

**Issue by MusicGivesMeLife** [pop4959/LWCX#133]
**LWC Version (2.2.6):** 
**Server version (1.15):** 

Multiple "Unable to add new block" errors in server log that seem normal but are very noisy (about a dozen instances) in the main server log

I cleared the lwc_blocks table and the errors went away, but reappeared the next time the server was restarted.  I'm assuming this is just LWCX ensuring all blocks are loaded into lwc_blocks, but it doesn't seem very efficient.  Possibly the offending function could do with a try/except statement to make these errors less dramatic.

```
[18:34:49] [Server thread/INFO]: [LWC] Unable to add new block to lwc_blocks!
[18:34:49] [Server thread/WARN]: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: lwc_blocks.id)
[18:34:49] [Server thread/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:941)
[18:34:49] [Server thread/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:953)
[18:34:49] [Server thread/WARN]: 	at org.sqlite.core.DB.execute(DB.java:854)
[18:34:49] [Server thread/WARN]: 	at org.sqlite.core.DB.executeUpdate(DB.java:895)
[18:34:49] [Server thread/WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102)
[18:34:49] [Server thread/WARN]: 	at com.griefcraft.cache.BlockCache.addBlock(BlockCache.java:154)
[18:34:49] [Server thread/WARN]: 	at com.griefcraft.cache.BlockCache.addBlock(BlockCache.java:174)
[18:34:49] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.doUpdateLWCX(PhysDB.java:2286)
[18:34:49] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.load(PhysDB.java:425)
[18:34:49] [Server thread/WARN]: 	at com.griefcraft.lwc.LWC.load(LWC.java:1726)
[18:34:49] [Server thread/WARN]: 	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:401)
[18:34:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:34:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[18:34:49] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[18:34:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
[18:34:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
[18:34:49] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:236)
[18:34:49] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885)
[18:34:49] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by MusicGivesMeLife** [comment]
Alright I found the issue, if the lwc_protections table has data that are too old it seriously confuses LWCX and it thinks it has to update the database file for 1.13+ *every time* it loads.  In case anyone else has the same issue, I'm including the SQL commands I used to clean out all the deprecated entries instead of just dropping the whole table.  Plus I manually dropped all the entries in lwc_blocks using sqlitebrowser.

```
DELETE FROM lwc_protections WHERE [blockName] IS NULL;
DELETE FROM lwc_protections WHERE LENGTH(owner) < 20;
DELETE FROM lwc_history WHERE LENGTH(player) < 20;
DELETE FROM lwc_protections WHERE [data] IS NUL;
DELETE FROM lwc_protections WHERE [blockId] IS NULL;
DELETE FROM lwc_protections WHERE [world] NOT IN ("MyWorld", "MyWorld_the_end", "MyWorld_nether");
```

**Comment by pop4959** [comment]
Sorry for the late response, I got an email about this issue yesterday but was just very busy.

You should normally never see that error, except if there is a problem with LWC or your database. It looks like in this case it may  be an issue with the automatic database updater, since it looks like the trace is coming from `doUpdateLWCX` which should only be run once per database.

If I recall correctly, the automatic updater for 1.13+ was tested to work correctly with the original Hidendra version of LWC, and also Modern-LWC. You're the first person in a long time to report an error with it. Would you be able to detail what your update process was like (versions of LWC, versions of Minecraft, etc)?

It could also be helpful, if possible, to have a copy of your old unfixed database file to see if I can more quickly identify where the update process failed. If you would like to send this privately, my Discord account is pop4959#1781.
