### ISSUE TITLE
Errors while doing cleanup

### ISSUE THREAD

**Issue by MinecraftCitiesNetwork** [pop4959/LWCX#139]
**LWC Version (/lwc admin version):** 
2.2.6-2d10269
**Server version (/version):** 
git-paper-320
**Short five word summary of issue:** 
Database locked error on cleanup
**Detailed description of problem:**
I'm getting database file is locked while running /lwc admin cleanup

**If there was an error in console, put it here:**
```
[07:13:09 WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[07:13:09 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1010)
[07:13:09 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1022)
[07:13:09 WARN]:        at org.sqlite.core.DB.throwex(DB.java:987)
[07:13:09 WARN]:        at org.sqlite.core.DB.exec(DB.java:185)
[07:13:09 WARN]:        at org.sqlite.SQLiteConnection.commit(SQLiteConnection.java:404)
[07:13:09 WARN]:        at com.griefcraft.sql.Database.setAutoCommit(Database.java:172)
[07:13:09 WARN]:        at com.griefcraft.util.DatabaseThread.flushDatabase(DatabaseThread.java:153)
[07:13:09 WARN]:        at com.griefcraft.util.DatabaseThread.run(DatabaseThread.java:179)
[07:13:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by pop4959** [comment]
That's completely normal to see. Cleanup should not be run while the plugin is in use by players.
