### ISSUE TITLE
LWC outdated version message while using latest version. Java related issue?

### ISSUE THREAD

**Issue by MCLimited** [pop4959/LWCX#152]
**LWC Version (/lwc admin version):** 
LWCX-2.2.7

**Server version (/version):** 
This server is running Paper version git-Paper-642 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Short five word summary of issue:** 
plugin outdated error message

**Detailed description of problem:**
I am preparing to upgrade our server from standalone server to a network (due to multiple gamemodes). Due to the preparations I decided to use JAVA 11 since JAVA 8 is not supported anymore from 1.17 and above.

When I start the server with LWC i get below error message:

**If there was an error in console, put it here:**
```
[18:09:28 INFO]:   LWC detected but its outdated. Please update it to latest version.
[18:09:28 WARN]: java.lang.NoClassDefFoundError: com/griefcraft/lwc/LWCPlugin
[18:09:28 WARN]:        at com.Zrips.CMI.CMI.setupLWC(CMI.java:1704)
[18:09:28 WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1631)
[18:09:28 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:09:28 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[18:09:28 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[18:09:28 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[18:09:28 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[18:09:28 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:591)
[18:09:28 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281)
[18:09:28 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065)
[18:09:28 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[18:09:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
[18:09:28 WARN]: Caused by: java.lang.ClassNotFoundException: com.griefcraft.lwc.LWCPlugin
[18:09:28 WARN]:        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[18:09:28 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182)
[18:09:28 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111)
[18:09:28 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[18:09:28 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[18:09:28 WARN]:        ... 12 more
```

**Comment by pop4959** [comment]
This message is not printed by LWC, it's printed by CMI as you can see from that error trace. The class [com/griefcraft/lwc/LWCPlugin](https://github.com/pop4959/LWCX/blob/master/src/main/java/com/griefcraft/lwc/LWCPlugin.java) still exists in the current version of LWC. I would report this to CMI since there seems to be something wrong with how they're checking this.
