### ISSUE TITLE
com.griefcraft.scripting.ModuleException: java.sql.SQLException: Field 'id' doesn't have a default value

### ISSUE THREAD

**Issue by BranTheOtter** [pop4959/LWCX#166]
**LWC Version (/lwc admin version):** 

2.28-DEV

**Server version (/version):** 

Paper 1.17.1

**Short five word summary of issue:** 

Transferred Data from provider to provider

**Detailed description of problem:**

Transferred Data from provider to provider

**If there was an error in console, put it here:**
```
[00:30:14 WARN]: com.griefcraft.scripting.ModuleException: java.sql.SQLException: Field 'id' doesn't have a default value
[00:30:14 WARN]:        at com.griefcraft.sql.Database.printException(Database.java:185)
[00:30:14 WARN]:        at com.griefcraft.sql.PhysDB.registerProtection(PhysDB.java:1268)
[00:30:14 WARN]:        at com.griefcraft.listeners.LWCBlockListener.onBlockPlaceMonitor(LWCBlockListener.java:523)
[00:30:14 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor58.execute(Unknown Source)
[00:30:14 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[00:30:14 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[00:30:14 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:30:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[00:30:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:387)
[00:30:14 WARN]:        at net.minecraft.world.item.ItemStack.placeItem(ItemStack.java:372)
[00:30:14 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:569)
[00:30:14 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1723)
[00:30:14 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
[00:30:14 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[00:30:14 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
```

**Comment by pop4959** [comment]
Can you give more details on how this happened? Did you update to the dev builds? The only thing I could think of recently that could potentially cause this is #160. Try on 2.2.7 and see if you're still getting the error.

**Comment by pop4959** [comment]
@BrandsPickled Did you only receive this error when transferring between hosts?

**Comment by pop4959** [comment]
Closing due to no response. If this is reported again with more details I will look into it.
