### ISSUE TITLE
Cannot invoke "Object.toString()" because "argument" is null

### ISSUE THREAD

**Issue by andrewkm** [pop4959/LWCX#187]
**LWC Version (/lwc admin version):** 
Built on https://github.com/pop4959/LWCX/commit/52b334ef161c0f42f7ce9701a5dcf254a8fa1a49
**Server version (/version):** 
Paper 1.17.1 Build 409 (Latest 1.17.1)
**Short five word summary of issue:** 
Console. Warning. Big. Sad. Help.
**Detailed description of problem:**
Caught this randomly in console today...
https://pastebin.com/raw/qbSJx3dJ
```
[12:56:13] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "Object.toString()" because "argument" is null
[12:56:13] [Server thread/WARN]: 	at LWCX-2.2.8-dev.jar//com.griefcraft.lwc.SimpleMessageParser.parseMessage(SimpleMessageParser.java:82)
[12:56:13] [Server thread/WARN]: 	at LWCX-2.2.8-dev.jar//com.griefcraft.lwc.LWC.getLocaleMessage(LWC.java:917)
[12:56:13] [Server thread/WARN]: 	at LWCX-2.2.8-dev.jar//com.griefcraft.lwc.LWC.sendLocaleToActionBar(LWC.java:988)
[12:56:13] [Server thread/WARN]: 	at LWCX-2.2.8-dev.jar//com.griefcraft.lwc.LWC.enforceAccess(LWC.java:708)
[12:56:13] [Server thread/WARN]: 	at LWCX-2.2.8-dev.jar//com.griefcraft.listeners.LWCPlayerListener.onPlayerInteract(LWCPlayerListener.java:683)
[12:56:13] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor31.execute(Unknown Source)
[12:56:13] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[12:56:13] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[12:56:13] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:56:13] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[12:56:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543)
[12:56:13] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:542)
[12:56:13] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1815)
[12:56:13] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
[12:56:13] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[12:56:13] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[12:56:13] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:56:13] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[12:56:13] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[12:56:13] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1426)
[12:56:13] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[12:56:13] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[12:56:13] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1404)
[12:56:13] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
[12:56:13] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110)
[12:56:13] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1536)
[12:56:13] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1282)
[12:56:13] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[12:56:13] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by andrewkm** [comment]
PS: Haven't had an LWC warning in months lol, wondering what happened here.

**Comment by pop4959** [comment]
Without further information it's not really possible to tell exactly what problem caused this error, but it is most likely due to either having a null owner on a protection (which is invalid, you should check your database for such entries) or unable to parse the name for a block/entity while interacting with a protection.

I've "fixed" the error itself in the latest dev build by adjusting the message parser to allow for null replacing a placeholder. While it doesn't actually address the problem itself, if you encounter it again it will be obvious in the message which protection is causing it and which part of the message it is failing to parse. Assuming it is not an issue with your database, we can then look at a more proper fix.

**Comment by andrewkm** [comment]
Thanks!
I've just checked our database and verified we have no null owners as well.
Will continue to monitor to see if anything comes up. :)
