### ISSUE TITLE
Bug limitsv2: Previous 1.14 material not recognize

### ISSUE THREAD

**Issue by JohOply** [pop4959/LWCX#19]
**LWC Version (/lwc admin version):** 2.1.8 (and dev builds)
**Server version (/version):** git-Spigot-1a3504a-84f3da3 (MC: 1.13.2)

**Short five word summary of issue:** Materials for which the name was change in 1.14 are not recognized in previous versions

**Detailed description of problem:**

In your latest versions, materials seems not be recognized by limitsv2.yml if they don't have 1.14 minecraft format.

For instance "sign" item changed in 1.14, with many types of wood. If I just use "SIGN" in limitsv2.yml, there is an internal error when I use /climits.

```
defaults:
    default: 150
    sign: 5
```

/climits in 2.1.2 (before update Modern LWC to LWCX) : https://i.imgur.com/CBwXeMv.png
/climits in 2.1.8 (has to work, but it doesn't) : https://i.imgur.com/JWrhlTO.png

```[18:21:25 INFO]: JohOply issued server command: /climits
[18:21:25 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'climits' in plugin LWC v2.1.8-540fc03
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[spigot-1.13.2-b2148b.jar:git-Spigot-1a3504a-84f3da3]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2-b2148b.jar:git-Spigot-1a3504a-84f3da3]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2-b2148b.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1621) ~[spigot-1.13.2-b2148b.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1461) ~[spigot-1.13.2-b2148b.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2-b2148b.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2-b2148b.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2-b2148b.jar:git-Spigot-1a3504a-84f3da3]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2-b2148b.jar:git-Spigot-1a3504a-84f3da3]
at net.minecr
aft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2-b2148b.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2-b2148b.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2-b2148b.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2-b2148b.jar:git-Spigot-1a3504a-84f3da3]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 2.1.8
at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:391) ~[?:?]
at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:171) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2-b2148b.jar:git-Spigot-1a3504a-84f3da3]
... 15 more
Caused by: java.lang.NoSuchFieldError: OAK_SIGN
at com.griefcraft.modules.limits.LimitsV2.sendLimits(LimitsV2.java:356) ~[?:?]
at com.griefcraft.modules.limits.LimitsV2.onCommand(LimitsV2.java:315) ~[?:?]
at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:367) ~[?:?]
at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:171) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2-b2148b.jar:git-Spigot-1a3504a-84f3da3]
... 15 more
```

If I use "OAK_SIGN", there isn't error but nothing is displayed, because item doesn't exist in 1.13.

```
defaults:
    default: 150
    oak_sign: 5
```

/climits modified in 2.1.8 : https://i.imgur.com/etF9jzO.png

Could you fix it to be able to still use 1.13.2 with latest versions please?

Thanks for reading

**Comment by pop4959** [comment]
Ah, I didn't realize from our previous conversation that this was just an NSFE. I'll fix it as soon as I can, shouldn't be a problem. It's definitely my fault, just an oversight as I'm a bit new to handling multi-version code.

By the way, it should only be an issue with the command. If anything else is broken let me know, but I don't think it's likely.

**Comment by JohOply** [comment]
What is NSFE?

I probably explained with more details here, no worries

**Comment by pop4959** [comment]
NoSuchFieldError

**Comment by pop4959** [comment]
Should be fixed in the latest development build.

**Comment by JohOply** [comment]
Seems fixed yeah :)
