### ISSUE TITLE
1.20 Console Errors

### ISSUE THREAD

**Issue by thelabcorner** [pop4959/LWCX#213]
**LWC Version (/lwc admin version):** 
 LWC v2.2.9-dev-571e72d

**Server version (/version):** 
[06:21:04 INFO]: This server is running Paper version git-Paper-"4b5f847" (MC: 1.20) (Implementing API version 1.20) (Git: 4b5f847 on dev/1.20)

**Short five word summary of issue:** 
Running the latest version from Ender Zone - with commit comment stating you had updated with 1.20 matchers, however upon loading in a test server; I'm receiving some YAML-related errors.

I understand 1.20 has just released, I just wanted to report because I believe WorldEdit/WorldGuard had a similar issue and wanted to share; perhaps you can reference it! https://github.com/EngineHub/WorldEdit/commit/bc0e6bbf0cae8abf2029ef7f4e48fab14559187b

**If there was an error in console, put it here:**
```
[06:21:16` INFO]: [LWC] Enabling LWC v2.2.9-dev-571e72d
[06:21:16 ERROR]: Error occurred while enabling LWC v2.2.9-dev-571e72d (Is it up to date?)
java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
        at com.griefcraft.util.config.Configuration.<init>(Configuration.java:69) ~[LWCX-2.2.9-dev.jar:?]
        at com.griefcraft.util.config.Configuration.load(Configuration.java:136) ~[LWCX-2.2.9-dev.jar:?]
        at com.griefcraft.util.config.Configuration.load(Configuration.java:105) ~[LWCX-2.2.9-dev.jar:?]
        at com.griefcraft.lwc.LWC.<init>(LWC.java:185) ~[LWCX-2.2.9-dev.jar:?]
        at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:346) ~[LWCX-2.2.9-dev.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.jar:git-Paper-"4b5f847"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.jar:git-Paper-"4b5f847"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.20.jar:git-Paper-"4b5f847"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.20.jar:git-Paper-"4b5f847"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.jar:git-Paper-"4b5f847"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1103) ~[paper-1.20.jar:git-Paper-"4b5f847"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.20.jar:git-Paper-"4b5f847"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[06:21:16 INFO]: [LWC] Disabling LWC v2.2.9-dev-571e72d 
```

**Side-Note**
This has added an incredibly valuable layer of protection and peace to so many Minecraft communities. Your consistent updates and commitment to maintaining the plugin does not go unnoticed. Many users, when they think of chest and door protection on Minecraft servers, immediately think of LWC, and that speaks more than a short paragraph ever could. Thank you for everything you do, and have done, to make our gameplay experience much better. ❤️

**Comment by pop4959** [comment]
Fixed in https://github.com/pop4959/LWCX/commit/1ceb5cbe2f9e7d0004c82673a0d5e8718eef1b79
