### ISSUE TITLE
cprivate owner:player error

### ISSUE THREAD

**Issue by seema84** [pop4959/LWCX#226]
Hey pop <3

**LWC Version (/lwc admin version):** 
2.3.1
**Server version (/version):** 
Paper version git-Paper-196 (MC: 1.20.1)
**Short five word summary of issue:** 
use command /cprivate owner:coco_is_cake
**Detailed description of problem:**
With some players (not all) I get this error message.
But the protection is given correctly.

**If there was an error in console, put it here:**
```
[18:53:53] [Server thread/INFO]: Seema issued server command: /cprivate owner:coco_is_cake
[18:53:57] [Server thread/WARN]: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 2.3.1
[18:53:57] [Server thread/WARN]: 	at LWC-2.3.1.jar//com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:391)
[18:53:57] [Server thread/WARN]: 	at LWC-2.3.1.jar//com.griefcraft.listeners.LWCPlayerListener.onPlayerInteract(LWCPlayerListener.java:679)
[18:53:57] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor25.execute(Unknown Source)
[18:53:57] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[18:53:57] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[18:53:57] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:53:57] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[18:53:57] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[18:53:57] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[18:53:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:591)
[18:53:57] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:537)
[18:53:57] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2015)
[18:53:57] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[18:53:57] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[18:53:57] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[18:53:57] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:53:57] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[18:53:57] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[18:53:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1338)
[18:53:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[18:53:57] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[18:53:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1315)
[18:53:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1308)
[18:53:57] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[18:53:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1286)
[18:53:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[18:53:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[18:53:57] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:53:57] [Server thread/WARN]: Caused by: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 2.3.1
[18:53:57] [Server thread/WARN]: 	at LWC-2.3.1.jar//com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:391)
[18:53:57] [Server thread/WARN]: 	at LWC-2.3.1.jar//com.griefcraft.modules.create.CreateModule.onBlockInteract(CreateModule.java:190)
[18:53:57] [Server thread/WARN]: 	at LWC-2.3.1.jar//com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:359)
[18:53:57] [Server thread/WARN]: 	... 27 more
[18:53:57] [Server thread/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.command.CommandSender.getName()" because "sender" is null
[18:53:57] [Server thread/WARN]: 	at LWC-2.3.1.jar//com.griefcraft.cache.DefaultsCache.getOrLoad(DefaultsCache.java:32)
[18:53:57] [Server thread/WARN]: 	at LWC-2.3.1.jar//com.griefcraft.modules.modifydefault.DefaultModule.onPostRegistration(DefaultModule.java:63)
[18:53:57] [Server thread/WARN]: 	at LWC-2.3.1.jar//com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:377)
[18:53:57] [Server thread/WARN]: 	... 29 more
```

**Comment by pop4959** [comment]
I'll take a look in a bit but at first glance this seems to be related to using protection defaults.

**Comment by pop4959** [comment]
Please take a look at the defaults (from `/cdefault`) for the players that are experiencing issues here and any additional relevant information.

Also if you can confirm whether this is only an issue when running the specific command you mentioned vs just `/cprivate`.

**Comment by seema84** [comment]
I have just tested it again without defaults (of the player and me), but the error remains the same. The player in question never had defaults, only me had used another player (which I had removed for the test).
If I create the backup with /cprivate and then do /lwc admin forceowner, I don't get an error message.

**Comment by pop4959** [comment]
Looking at it again, this is just missing a null check anyway so regardless of how to reproduce, it is a bug. I just patched the place where this would happen so it shouldn't happen anymore. Thanks!

**Comment by seema84** [comment]
Thank you, the problem has been fixed.
