### ISSUE TITLE
LWC cannot be used

### ISSUE THREAD

**Issue by Re-Aqest** [pop4959/LWCX#230]
**LWC Version (/lwc admin version):** 
2.3.2
**Server version (/version):** 
MohistServer  1.20.1 588
**Short five word summary of issue:** 
Unable to lock the box
**Detailed description of problem:**
When entering the server, the player server card, and the plug-in can not be used at all

**If there was an error in console, put it here:**
```
[01:27:23 WARN]: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 2.3.2
[01:27:23 WARN]:        at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:391)
[01:27:23 WARN]:        at com.griefcraft.listeners.LWCBlockListener.onBlockPlaceMonitor(LWCBlockListener.java:545)
[01:27:23 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[01:27:23 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[01:27:23 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[01:27:23 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:27:23 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:602)
[01:27:23 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:586)
[01:27:23 WARN]:        at TRANSFORMER/forge@47.2.20/com.mohistmc.eventhandler.dispatcher.BlockEventDispatcher.onBlockPlace(BlockEventDispatcher.java:148)
[01:27:23 WARN]:        at TRANSFORMER/forge@47.2.20/com.mohistmc.eventhandler.dispatcher.__BlockEventDispatcher_onBlockPlace_EntityPlaceEvent.invoke(.dynamic)
[01:27:23 WARN]:        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
[01:27:23 WARN]:        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:319)
[01:27:23 WARN]:        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:299)
[01:27:23 WARN]:        at TRANSFORMER/forge@47.2.20/net.minecraftforge.event.ForgeEventFactory.onBlockPlace(ForgeEventFactory.java:183)
[01:27:23 WARN]:        at TRANSFORMER/forge@47.2.20/net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:630)
[01:27:23 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:297)
[01:27:23 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:490)
[01:27:23 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1553)
[01:27:23 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34)
[01:27:23 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8)
[01:27:23 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:25)
[01:27:23 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
[01:27:23 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
[01:27:23 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[01:27:23 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1029)
[01:27:23 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:173)
[01:27:23 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
[01:27:23 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1012)
[01:27:23 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1006)
[01:27:23 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
[01:27:23 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:992)
[01:27:23 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:908)
[01:27:23 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281)
[01:27:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[01:27:23 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "org.anjocaido.groupmanager.GroupManager.getWorldsHolder()" because "this.groupManager" is null
[01:27:23 WARN]:        at net.milkbowl.vault.permission.plugins.Permission_GroupManager.getPlayerGroups(Permission_GroupManager.java:311)
[01:27:23 WARN]:        at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:637)
[01:27:23 WARN]:        at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:649)
[01:27:23 WARN]:        at com.griefcraft.integration.permissions.VaultPermissions.getGroups(VaultPermissions.java:56)
[01:27:23 WARN]:        at com.griefcraft.modules.limits.LimitsV2.getPlayerLimits(LimitsV2.java:554)
[01:27:23 WARN]:        at com.griefcraft.modules.limits.LimitsV2.getEffectiveLimit(LimitsV2.java:594)
[01:27:23 WARN]:        at com.griefcraft.modules.limits.LimitsV2.hasReachedLimit(LimitsV2.java:446)
[01:27:23 WARN]:        at com.griefcraft.modules.limits.LimitsV2.onRegisterProtection(LimitsV2.java:298)
[01:27:23 WARN]:        at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:373)
[01:27:23 WARN]:        ... 33 more
```

**Comment by pop4959** [comment]
This is an invalid bug report since you are using unsupported software. LWC does not support Forge servers.
