### ISSUE TITLE
Destroying Chiseled Bookshelf triggers LWC internal error

### ISSUE THREAD

**Issue by Sotomura** [pop4959/LWCX#243]
**LWC Version (/lwc admin version):** 
2.4.0

**Server version (/version):** 
This server is running Paper version 1.21.4-32-main@b8a0541 (2024-12-24T10:07:40Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.4-25-17f649d (MC: 1.21.4)

**Short five word summary of issue:** 
Destroying Chiseled Bookshelf causes error

**Detailed description of problem:**
Attempting to destroy a Chiseled Bookshelf from the front (where the books themselves are stored) causes an Internal Error to occur. The block will not be destroyed.

This issue does not occur when attempting to mine the block from any other side.

**If there was an error in console, put it here:**
```
[11:43:12] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.util.Vector.clone()" because "this.clickedPosistion" is null
[11:43:12] [Server thread/WARN]: 	at org.bukkit.event.player.PlayerInteractEvent.getClickedPosition(PlayerInteractEvent.java:244)
[11:43:12] [Server thread/WARN]: 	at LWC-2.4.0.jar//com.griefcraft.listeners.LWCPlayerListener.onPlayerInteract(LWCPlayerListener.java:613)
[11:43:12] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor29.execute(Unknown Source)
[11:43:12] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[11:43:12] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[11:43:12] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:43:12] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[11:43:12] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[11:43:12] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[11:43:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:603)
[11:43:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:559)
[11:43:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:554)
[11:43:12] [Server thread/WARN]: 	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:181)
[11:43:12] [Server thread/WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1841)
[11:43:12] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51)
[11:43:12] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:10)
[11:43:12] [Server thread/WARN]: 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:29)
[11:43:12] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:43:12] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155)
[11:43:12] [Server thread/WARN]: 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[11:43:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1448)
[11:43:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:176)
[11:43:12] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129)
[11:43:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428)
[11:43:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1422)
[11:43:12] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:118)
[11:43:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1561)
[11:43:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251)
[11:43:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
[11:43:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Sotomura** [comment]
Paper issue. Fixed in 1.21.4-41.
