### ISSUE TITLE
Failed to break blocks

### ISSUE THREAD

**Issue by brenoxavier** [pop4959/LWCX#59]
**LWC Version (/lwc admin version):** 1.9.7
**Server version (/version):** 1.8.8

**Short five word summary of issue:** Failed to break blocks

**Detailed description of problem:** After i remove my own block, if someone put one at the same place, i become the owner. How can i solve this??

**Comment by pop4959** [comment]
This can happen for a variety of reasons, but the most common is if you use another plugin to break the block. For example, if you use `/break` in Essentials, or `//set` in WorldEdit.

If the above is true, there are several ways to fix this. If it is only one block that is protected incorrectly, simply use `/unlock` or `/lwc admin forceowner <player>` on the location. If you have WorldGuard installed, you also have the option of removing protections from an entire region using `/lwc admin purgeregion <region>`. If you want to remove all ghost protections in the entire world, use `/lwc admin cleanup` although keep in mind that this can cause lag, and you may not want to do it on a server while there are players online.

Let me know if this solves the problem for you.

**Comment by brenoxavier** [comment]
I did not remove the block using plugins. When I break the block manually, the phantom block remains in place even using **/lwc cleanup**. When I typed **/lwc purge**, the following error occurred:
```
[14:00:58] [Server thread/INFO]: You have:[0;32;22m 1[0;37;1m protections. [m
[14:00:58] [Server thread/INFO]: [0;31;22mThis may take a while depending on how many protections you have[m
[14:00:58] [Thread-26/INFO]: [0;31;22mProcessing cleanup request now in a separate thread[m
[14:01:01] [Thread-26/INFO]: Removed (noexist): Private Chest[0;37;1m [0;32;22mId=1 Owner=cc319681-27ff-3072-baf6-c0f3be402a40 Location=[mundo 708,68,785] Created=2019-12-19 13:59:51.794 Flags= LastAccessed=11 seconds ago[m
[14:01:01] [Thread-26/INFO]: [0;31;22mCleanup @ 100% [ 1/1 protections ] [ removed 1 protections ][m
[14:01:01] [Thread-26/INFO]: Exception caught during cleanup: database is locked
[14:01:01] [Thread-26/WARN]: java.sql.SQLException: database is locked
[14:01:01] [Thread-26/WARN]: 	at org.sqlite.NativeDB.throwex(NativeDB.java:210)
[14:01:01] [Thread-26/WARN]: 	at org.sqlite.NativeDB._exec(Native Method)
[14:01:01] [Thread-26/WARN]: 	at org.sqlite.Stmt.executeUpdate(Stmt.java:152)
[14:01:01] [Thread-26/WARN]: 	at com.griefcraft.modules.admin.AdminCleanup$Admin_Cleanup_Thread.push(AdminCleanup.java:141)
[14:01:01] [Thread-26/WARN]: 	at com.griefcraft.modules.admin.AdminCleanup$Admin_Cleanup_Thread.run(AdminCleanup.java:279)
[14:01:01] [Thread-26/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:01:08] [Server thread/INFO]: Opped AsyNc_
[14:01:21] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'lwc' in plugin LWC v1.9.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_232]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 1.9.7
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:393) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:174) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	... 15 more
Caused by: com.griefcraft.scripting.ModuleException: java.sql.SQLException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at com.griefcraft.sql.Database.printException(Database.java:212) ~[?:?]
	at com.griefcraft.sql.PhysDB.fetch(PhysDB.java:128) ~[?:?]
	at com.griefcraft.sql.PhysDB.getProtectionCount(PhysDB.java:140) ~[?:?]
	at com.griefcraft.modules.admin.AdminCleanup.onCommand(AdminCleanup.java:90) ~[?:?]
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:369) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:174) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	... 15 more
Caused by: java.sql.SQLException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at org.sqlite.DB.newSQLException(DB.java:383) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.sqlite.DB.newSQLException(DB.java:387) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.sqlite.DB.execute(DB.java:339) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.sqlite.PrepStmt.executeQuery(PrepStmt.java:75) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at com.griefcraft.sql.PhysDB.fetch(PhysDB.java:120) ~[?:?]
	at com.griefcraft.sql.PhysDB.getProtectionCount(PhysDB.java:140) ~[?:?]
	at com.griefcraft.modules.admin.AdminCleanup.onCommand(AdminCleanup.java:90) ~[?:?]
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:369) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:174) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	... 15 more
[14:01:31] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'lwc' in plugin LWC v1.9.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_232]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 1.9.7
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:393) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:174) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	... 15 more
Caused by: com.griefcraft.scripting.ModuleException: java.sql.SQLException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at com.griefcraft.sql.Database.printException(Database.java:212) ~[?:?]
	at com.griefcraft.sql.PhysDB.fetch(PhysDB.java:128) ~[?:?]
	at com.griefcraft.sql.PhysDB.getProtectionCount(PhysDB.java:140) ~[?:?]
	at com.griefcraft.lwc.LWC.fastRemoveProtections(LWC.java:1049) ~[?:?]
	at com.griefcraft.lwc.LWC.fastRemoveProtectionsByPlayer(LWC.java:1016) ~[?:?]
	at com.griefcraft.modules.admin.AdminPurge.onCommand(AdminPurge.java:72) ~[?:?]
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:369) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:174) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	... 15 more
Caused by: java.sql.SQLException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at org.sqlite.DB.newSQLException(DB.java:383) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.sqlite.DB.newSQLException(DB.java:387) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.sqlite.DB.execute(DB.java:339) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.sqlite.PrepStmt.executeQuery(PrepStmt.java:75) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at com.griefcraft.sql.PhysDB.fetch(PhysDB.java:120) ~[?:?]
	at com.griefcraft.sql.PhysDB.getProtectionCount(PhysDB.java:140) ~[?:?]
	at com.griefcraft.lwc.LWC.fastRemoveProtections(LWC.java:1049) ~[?:?]
	at com.griefcraft.lwc.LWC.fastRemoveProtectionsByPlayer(LWC.java:1016) ~[?:?]
	at com.griefcraft.modules.admin.AdminPurge.onCommand(AdminPurge.java:72) ~[?:?]
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:369) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:174) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	... 15 more
```

**Comment by pop4959** [comment]
That error can occur normally. SQLITE_BUSY means you tried to access the database while it was locked. Typically that means that there were players online trying to use LWC while you were running the cleanup utility. As I mentioned in the above post, you do not want to run cleanup while there are players online. It's something you only want to use during server maintenance.

As for your original issue, that is very peculiar. This is the first time I have heard of ghost blocks occurring from normal placement/breakage. Try these 3 things and tell me if any of them seems to fix your issue: 1) restart the server, especially if it has been running for a long time or you have used any commands such as /reload. 2) remove all other plugins and see if LWC works properly without them installed. 3) temporarily move lwc.db from the LWC folder and restart the server, see if the issue occurs with a freshly generated database.

Look forward to hearing back from you. Also, since this issue grows more complicated, feel free to hop on the [Discord server](https://discord.gg/PHpuzZS) to chat with me one-on-one about this. It might be faster and easier to find out the problem that way. I'm available frequently, just ping me in the LWC channel.

**Comment by brenoxavier** [comment]
I added the lwc.flag.exemption permission and it worked the right way.

Thank's for your time!

**Comment by pop4959** [comment]
You're welcome. Maybe I've misunderstood something, because that flag permission shouldn't really do anything to affect this. Or perhaps it just fixed itself as a result of something else. Either way, glad it's no longer an issue. :smiley:
