### ISSUE TITLE
Factions does not work with newest version

### ISSUE THREAD

**Issue by nick-perry14** [pop4959/LWCX#66]
**LWC Version (/lwc admin version):** 
2.2.3-9cd94a3
**Server version (/version):** 
1.15.1
**Short five word summary of issue:** 
Factions cannot find a class
**Detailed description of problem:**

The factions plugin fails to hook into the newer factions plugin.  I looked in the github repo and the FPlayer class DOES NOT exist.  However, a "MPlayer" class does exist.  Not sure if they are identical.

**If there was an error in console, put it here:**
```
[04:49:58 INFO]: [LWC] Enabling LWC v2.2.3-9cd94a3
[04:49:59 INFO]: [LWC] Failed to hook into Factions! (Is it up to date?)
[04:49:59 WARN]: java.lang.NoClassDefFoundError: com/massivecraft/factions/FPlayer
[04:49:59 WARN]: at java.lang.Class.getDeclaredMethods0(Native Method)
[04:49:59 WARN]: at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[04:49:59 WARN]: at java.lang.Class.getDeclaredMethods(Class.java:1975)
[04:49:59 WARN]: at com.griefcraft.scripting.ModuleLoader.doesObjectOverrideMethod(ModuleLoader.java:332)
[04:49:59 WARN]: at com.griefcraft.scripting.ModuleLoader.registerFastCache(ModuleLoader.java:242)
[04:49:59 WARN]: at com.griefcraft.scripting.ModuleLoader.registerModule(ModuleLoader.java:502)
[04:49:59 WARN]: at com.griefcraft.lwc.LWC.registerModule(LWC.java:1871)
[04:49:59 WARN]: at com.griefcraft.lwc.LWC.registerCoreModules(LWC.java:1857)
[04:49:59 WARN]: at com.griefcraft.lwc.LWC.load(LWC.java:1725)
[04:49:59 WARN]: at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:400)
[04:49:59 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[04:49:59 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[04:49:59 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[04:49:59 WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468)
[04:49:59 WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382)
[04:49:59 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:227)
[04:49:59 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884)
[04:49:59 WARN]: at java.lang.Thread.run(Thread.java:748)
[04:49:59 WARN]: Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.FPlayer
[04:49:59 WARN]: at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[04:49:59 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139)
[04:49:59 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85)
[04:49:59 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[04:49:59 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[04:49:59 WARN]: ... 18 more```

**Comment by pop4959** [comment]
What version of factions are you using?

**Comment by nick-perry14** [comment]
2.15

**Comment by pop4959** [comment]
I'm not able to find that version. Can you give me a link to exactly where you got this?

**Comment by nick-perry14** [comment]
So, There were two, BOTH caused the same errors

https://www.spigotmc.org/resources/factions.1900/
https://www.spigotmc.org/resources/factions.73387/

**Comment by pop4959** [comment]
Ah that would be the problem. MassiveCraft's original Factions plugin is discontinued, and the other one you linked is most likely outdated. Our hook for Factions is designed for [FactionsUUID](https://www.spigotmc.org/resources/factionsuuid.1035/) or compatible derivative plugins. It is a freemium open source plugin, which you can either pay for to support the maintainers, download for free on their build server, or build yourself from [drtshock/Factions](https://github.com/drtshock/Factions).

**Comment by pop4959** [comment]
Improved the error message in 1b2beffbd21e1a42812ea0aa800747061d8c2701 so that others don't get confused.
