### ISSUE TITLE
Plugin folder not Found

### ISSUE THREAD

**Issue by KleinCrafter** [pop4959/LWCX#75]
**LWC Version (/lwc admin version):** 
2.2.4-dev-59b2359
**Server version (/version):** 
git-Paper-49 (MC: 1.15.1)
**Short five word summary of issue:** 
Plugin folder not Found

**Detailed description of problem:**
`java -jar paper.jar --plugins /share/plugins`

Log output:
```
[18:04:02] [Server thread/INFO]: [LWC] Enabling LWC v2.2.4-dev-59b2359
[18:04:02] [Server thread/WARN]: java.io.FileNotFoundException: plugins/LWC/core.yml (No such file or directory)
[18:04:02] [Server thread/WARN]:        at java.io.FileOutputStream.open0(Native Method)
[18:04:02] [Server thread/WARN]:        at java.io.FileOutputStream.open(FileOutputStream.java:270)
[18:04:02] [Server thread/WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[18:04:02] [Server thread/WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
[18:04:02] [Server thread/WARN]:        at com.griefcraft.util.config.Configuration.extractFile(Configuration.java:158)
[18:04:02] [Server thread/WARN]:        at com.griefcraft.util.config.Configuration.load(Configuration.java:133)
[18:04:02] [Server thread/WARN]:        at com.griefcraft.util.config.Configuration.load(Configuration.java:105)
[18:04:02] [Server thread/WARN]:        at com.griefcraft.lwc.LWC.<init>(LWC.java:218)
[18:04:02] [Server thread/WARN]:        at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:341)
[18:04:02] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:04:02] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[18:04:02] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[18:04:02] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468)
[18:04:02] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382)
[18:04:02] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:227)
[18:04:02] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884)
[18:04:02] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
```

https://github.com/pop4959/LWCX/search?q=plugins&unscoped_q=plugins
Replace `new File("/plugins/LWC/...")` with `new File(getDataFolder(), "...")`
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/plugin/java/JavaPlugin.html#getDataFolder--

**Comment by pop4959** [comment]
Should be fixed in 1f6f9db2e0264c50c488a55201532e8b5f8fcb90.
